---

services:
  jellyfin:
    container_name: jellyfin
    environment:
      - JELLYFIN_PublishedServerUrl="${FQDN}"
      - HOSTNAME="docker-jellyfin"
      - PUID="${GID}"
      - PGID="${UID}"
      - TZ="America/New_York"
    hostname: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=http"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: always
    volumes:
      - /data/apps/jellyfin:/config
      - /homes/bfrank/media:/data/movies
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  traefik:
    external: true
