api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
  file:
    directory: /rules
    watch: true

certificatesResolvers:
  http:
    acme:
      email: bradfrank@fastmail.com
      storage: ./letsencrypt/acme.json
      httpChallenge:
        entryPoint: http
