---

- name: Configure app server
  hosts: all
  tasks:

    - name: Ensure /srv directory exists
      ansible.builtin.file:
        path: /srv
        owner: root
        group: root
        mode: "0755"
        state: directory

    - name: Install app components
      ansible.posix.synchronize:
        src: apps/
        dest: /srv
        compress: false
        owner: false
        group: false

    - name: Create local users
      loop: "{{ apps | dict2items }}"
      loop_control:
        label: "{{ item['key'] }}"
      ansible.builtin.user:
        name: "{{ item['key'] }}"
        shell: /usr/sbin/nologin
        groups: [staff]
        create_home: false
        expires: -1
        password_expire_max: -1
        uid: "{{ item['value']['system_uid'] }}"
      when: item['value']['system_account']

    - name: Get 'staff' GID
      ansible.builtin.getent:
        database: group
        key: staff

    - name: Create traefik network
      community.docker.docker_network:
        name: traefik

    - name: Symlink Nextcloud cronjob
      ansible.builtin.file:
        src: /srv/nextcloud/cron
        dest: /etc/cron.d/nextcloud
        state: link
        force: true
