---

- name: Configure app server
  hosts: app
  tasks:

    - name: Ensure /srv directory exists
      ansible.builtin.file:
        path: /srv
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Install app components
      ansible.posix.synchronize:
        src: apps/
        dest: /srv
        compress: false
        owner: false
        group: false

    - name: Template Docker env file
      loop: "{{ lookup('community.general.filetree', 'apps/') }}"
      when: item['state'] == 'directory'
      ansible.builtin.template:
        src: "apps/{{ app }}.env.j2"
        dest: "/srv/{{ app }}/.env"
        mode: 0600

    - name: Symlink Nextcloud cronjob
      ansible.builtin.file:
        src: /srv/nextcloud/cron
        dest: /etc/cron.d/nextcloud
        state: link
        force: true
