- name: Print disk info
  hosts: all
  tasks:
    - name: Print disk information
      ansible.builtin.debug:
        msg: "/dev/{{ item['key'] }}: wwn-{{ item['value']['wwn'] }} ({{ item['value']['size'] }})"
      loop: "{{ ansible_devices | dict2items }}"
      loop_control:
        label: "{{ item['key'] }}"
      when: item['value']['wwn'] is defined
